engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - python
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.py"
