sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install enum34
    - pip install pylint
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - pip install Flask-Testing
    - pip install Jinja2
    - pip install SQLAlchemy

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test
