sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install enum34
    - pip install pylint
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - pip install Flask-Testing
    - pip install Jinja2
    - pip install SQLAlchemy
    - pip install flask_table
    - pip install psycopg2
    - pip install flask_whooshalchemyplus
    - pip install codeclimate-test-reporter

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test

addons:
    code_climate:
        repo_token: b587e799964870daedc7f4c0ee9e4dff047d3d2e8142a5ce6483d6b651583aa5
