FORMAT: 1A
HOST: http://www.sweatshop.tech/api

# SWEatshop.tech

SWEatshop is a simple API to retrieve centralized data regarding companies along with the people, investors and schools of everyone involved.

## People Collection [/person]

### List All People [GET]

+ Response 200 (application/json)

        [
            {
                "companies": [
                    {
                        "ceo_id": 1, 
                        "country": "United States", 
                        "crunch_id": null, 
                        "description": "Chowbotics uses robots to solve several problems in food service including compromised cleanliness and inefficiency.", 
                        "funding": 6300000, 
                        "idnum": 1, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1489162423/uihtpjzpzdmjjfftpjwu.png", 
                        "location": "San Jose", 
                        "name": "Chowbotics", 
                        "ownership_type": "PRIVATE", 
                        "size": 2, 
                        "website": "http://"
                    }
                ],
                "country": "United States", 
                "crunch_id": null, 
                "description": null, 
                "dob": "1975-06-02T00:00:00", 
                "idnum": 1, 
                "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1488973627/czyyg9bvkun0skdepnsn.png", 
                "location": "San Jose", 
                "name": "Deepak Sekar", 
                "schools": [
                    {
                        "country": "India", 
                        "description": "Indian Institute of Technology Madras", 
                        "idnum": 1, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1415957687/v2l8rpjmlodkqqedmbpe.jpg", 
                        "location": "Chennai", 
                        "name": "Indian Institute of Technology Madras", 
                        "size": 10000, 
                        "website": "http://www.iitm.ac.in"
                    }, 
                    {
                        "country": "United States", 
                        "description": "The Georgia Institute of Technology is a public research university in Atlanta, Georgia, in the United States.", 
                        "idnum": 2, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1452600927/wygblir8adecdfrokppd.jpg", 
                        "location": "Atlanta", 
                        "name": "Georgia Institute of Technology", 
                        "size": 26806, 
                        "website": "http://www.gatech.edu"
                    }
                ],
                "title": "CEO", 
                "website": "http://chowbotics.com"
            }
        ]

## Specific Person [/person/{person_id}]

+ Parameters
    + person_id (number) - id of the requested person in the form of an integer

### Specific Person [GET]

+ Response 200 (application/json)

        {
            "companies": [
                {
                    "ceo_id": 1, 
                    "country": "United States", 
                    "crunch_id": null, 
                    "description": "Chowbotics uses robots to solve several problems in food service including compromised cleanliness and inefficiency.", 
                    "funding": 6300000, 
                    "idnum": 1, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1489162423/uihtpjzpzdmjjfftpjwu.png", 
                    "location": "San Jose", 
                    "name": "Chowbotics", 
                    "ownership_type": "PRIVATE", 
                    "size": 2, 
                    "website": "http://"
                }
            ],
            "country": "United States", 
            "crunch_id": null, 
            "description": null, 
            "dob": "1975-06-02T00:00:00", 
            "idnum": 1, 
            "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1488973627/czyyg9bvkun0skdepnsn.png", 
            "location": "San Jose", 
            "name": "Deepak Sekar", 
            "schools": [
                {
                    "country": "India", 
                    "description": "Indian Institute of Technology Madras", 
                    "idnum": 1, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1415957687/v2l8rpjmlodkqqedmbpe.jpg", 
                    "location": "Chennai", 
                    "name": "Indian Institute of Technology Madras", 
                    "size": 10000, 
                    "website": "http://www.iitm.ac.in"
                }, 
                {
                    "country": "United States", 
                    "description": "The Georgia Institute of Technology is a public research university in Atlanta, Georgia, in the United States.", 
                    "idnum": 2, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1452600927/wygblir8adecdfrokppd.jpg", 
                    "location": "Atlanta", 
                    "name": "Georgia Institute of Technology", 
                    "size": 26806, 
                    "website": "http://www.gatech.edu"
                }
            ],
            "title": "CEO", 
            "website": "http://chowbotics.com"
        }

## Company Collection [/company]

### List All Companies [GET]

+ Response 200 (application/json)

        [
            {
                "ceo_id": 1, 
                "country": "United States", 
                "crunch_id": null, 
                "description": "Chowbotics uses robots to solve several problems in food service including compromised cleanliness and inefficiency.", 
                "employees": [
                    {
                        "country": "United States", 
                        "crunch_id": null, 
                        "description": null, 
                        "dob": "1975-06-02T00:00:00", 
                        "idnum": 1, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1488973627/czyyg9bvkun0skdepnsn.png", 
                        "location": "San Jose", 
                        "name": "Deepak Sekar", 
                        "title": "CEO", 
                        "website": "http://chowbotics.com"
                    }
                ],
                "funding": 6300000, 
                "idnum": 1, 
                "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1489162423/uihtpjzpzdmjjfftpjwu.png", 
                "investors": [
                    {
                        "country": "United States", 
                        "description": "The Geekdom Fund is a venture capital fund that invests in early stage IT startups in San Antonio, South Texas and beyond.", 
                        "funding": 3458000, 
                        "idnum": 1, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1407349059/czbs2zk9z5kz5dyvfbny.jpg", 
                        "location": "San Antonio", 
                        "name": "Geekdom Fund", 
                        "website": "http://www.geekdomfund.com"
                    }
                ],
                "location": "San Jose", 
                "name": "Chowbotics", 
                "ownership_type": "PRIVATE", 
                "size": 2, 
                "website": "http://"
            }
        ]

## Specific Company [/company/{company_id}]

+ Parameters
    + company_id (number) - id of the requested company in the form of an integer

### Specific Company [GET]

+ Response 200 (application/json)

        {
            "ceo_id": 1, 
            "country": "United States", 
            "crunch_id": null, 
            "description": "Chowbotics uses robots to solve several problems in food service including compromised cleanliness and inefficiency.", 
            "employees": [
                {
                    "country": "United States", 
                    "crunch_id": null, 
                    "description": null, 
                    "dob": "1975-06-02T00:00:00", 
                    "idnum": 1, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1488973627/czyyg9bvkun0skdepnsn.png", 
                    "location": "San Jose", 
                    "name": "Deepak Sekar", 
                    "title": "CEO", 
                    "website": "http://chowbotics.com"
                }
            ],
            "funding": 6300000, 
            "idnum": 1, 
            "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1489162423/uihtpjzpzdmjjfftpjwu.png", 
            "investors": [
                {
                    "country": "United States", 
                    "description": "The Geekdom Fund is a venture capital fund that invests in early stage IT startups in San Antonio, South Texas and beyond.", 
                    "funding": 3458000, 
                    "idnum": 1, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1407349059/czbs2zk9z5kz5dyvfbny.jpg", 
                    "location": "San Antonio", 
                    "name": "Geekdom Fund", 
                    "website": "http://www.geekdomfund.com"
                }
            ],
            "location": "San Jose", 
            "name": "Chowbotics", 
            "ownership_type": "PRIVATE", 
            "size": 2, 
            "website": "http://"
        }

## Schools Collection [/school]

### List All Schools [GET]

+ Response 200 (application/json)

        [
            {
                "alumni": [
                    {
                        "country": "United States", 
                        "crunch_id": null, 
                        "description": null, 
                        "dob": "1975-06-02T00:00:00", 
                        "idnum": 1, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1488973627/czyyg9bvkun0skdepnsn.png", 
                        "location": "San Jose", 
                        "name": "Deepak Sekar", 
                        "title": "CEO", 
                        "website": "http://chowbotics.com"
                    }, 
                    {
                        "country": "United States", 
                        "crunch_id": null, 
                        "description": null, 
                        "dob": "1962-01-12T00:00:00", 
                        "idnum": 3, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1397632836/052828bcd0edb674d3c6176413d58b81.jpg", 
                        "location": "New York", 
                        "name": "Dilip Keshu", 
                        "title": "CEO", 
                        "website": "http://borngroup.com"
                    }
                ],
                "country": "India", 
                "description": "Indian Institute of Technology Madras", 
                "idnum": 1, 
                "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1415957687/v2l8rpjmlodkqqedmbpe.jpg", 
                "investors": [
                    {
                        "country": "United States", 
                        "description": "Scale Venture Partners is a VC firm that invests in enterprise technology companies with a focus on SaaS and cloud infrastructure.", 
                        "funding": 1234000, 
                        "idnum": 3, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1397178826/f7ab3ffe2646afa0014c27dd1c036891.gif", 
                        "location": "Foster City", 
                        "name": "Scale Venture Partners", 
                        "website": "http://www.scalevp.com"
                    }
                ],
                "location": "Chennai", 
                "name": "Indian Institute of Technology Madras", 
                "size": 10000, 
                "website": "http://www.iitm.ac.in"
            }
        ]

## Specific School [/school/{school_id}]

+ Parameters
    + school_id (number) - id of the requested school in the form of an integer

### Specific School [GET]

+ Response 200 (application/json)

        {
            "alumni": [
                {
                    "country": "United States", 
                    "crunch_id": null, 
                    "description": null, 
                    "dob": "1975-06-02T00:00:00", 
                    "idnum": 1, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1488973627/czyyg9bvkun0skdepnsn.png", 
                    "location": "San Jose", 
                    "name": "Deepak Sekar", 
                    "title": "CEO", 
                    "website": "http://chowbotics.com"
                }, 
                {
                    "country": "United States", 
                    "crunch_id": null, 
                    "description": null, 
                    "dob": "1962-01-12T00:00:00", 
                    "idnum": 3, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1397632836/052828bcd0edb674d3c6176413d58b81.jpg", 
                    "location": "New York", 
                    "name": "Dilip Keshu", 
                    "title": "CEO", 
                    "website": "http://borngroup.com"
                }
            ],
            "country": "India", 
            "description": "Indian Institute of Technology Madras", 
            "idnum": 1, 
            "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1415957687/v2l8rpjmlodkqqedmbpe.jpg", 
            "investors": [
                {
                    "country": "United States", 
                    "description": "Scale Venture Partners is a VC firm that invests in enterprise technology companies with a focus on SaaS and cloud infrastructure.", 
                    "funding": 1234000, 
                    "idnum": 3, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1397178826/f7ab3ffe2646afa0014c27dd1c036891.gif", 
                    "location": "Foster City", 
                    "name": "Scale Venture Partners", 
                    "website": "http://www.scalevp.com"
                }
            ],
            "location": "Chennai", 
            "name": "Indian Institute of Technology Madras", 
            "size": 10000, 
            "website": "http://www.iitm.ac.in"
        }

## Investors Collection [/investor]

### List All Investors [GET]

+ Response 200 (application/json)

        [
            {
                "companies": [
                    {
                        "ceo_id": 1, 
                        "country": "United States", 
                        "crunch_id": null, 
                        "description": "Chowbotics uses robots to solve several problems in food service including compromised cleanliness and inefficiency.", 
                        "funding": 6300000, 
                        "idnum": 1, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1489162423/uihtpjzpzdmjjfftpjwu.png", 
                        "location": "San Jose", 
                        "name": "Chowbotics", 
                        "ownership_type": "PRIVATE", 
                        "size": 2, 
                        "website": "http://"
                    }
                ],
                "country": "United States", 
                "description": "The Geekdom Fund is a venture capital fund that invests in early stage IT startups in San Antonio, South Texas and beyond.", 
                "funding": 3458000, 
                "idnum": 1, 
                "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1407349059/czbs2zk9z5kz5dyvfbny.jpg", 
                "location": "San Antonio", 
                "name": "Geekdom Fund", 
                "schools": [
                    {
                        "country": "United States", 
                        "description": "Stanford University Graduate School of Business", 
                        "idnum": 3, 
                        "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1481309706/olvayk18i7e3t1mptejq.jpg", 
                        "location": "Stanford", 
                        "name": "Stanford University Graduate School of Business", 
                        "size": 1000, 
                        "website": "http://www.gsb.stanford.edu"
                    }
                ],
                "website": "http://www.geekdomfund.com"
            }
        ]

## Specific Investor [/investor/{investor_id}]

+ Parameters
    + investor_id (number) - id of the requested investor in the form of an integer

### Specific Investor [GET]

+ Response 200 (application/json)

        {
            "companies": [
                {
                    "ceo_id": 1, 
                    "country": "United States", 
                    "crunch_id": null, 
                    "description": "Chowbotics uses robots to solve several problems in food service including compromised cleanliness and inefficiency.", 
                    "funding": 6300000, 
                    "idnum": 1, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1489162423/uihtpjzpzdmjjfftpjwu.png", 
                    "location": "San Jose", 
                    "name": "Chowbotics", 
                    "ownership_type": "PRIVATE", 
                    "size": 2, 
                    "website": "http://"
                }
            ],
            "country": "United States", 
            "description": "The Geekdom Fund is a venture capital fund that invests in early stage IT startups in San Antonio, South Texas and beyond.", 
            "funding": 3458000, 
            "idnum": 1, 
            "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1407349059/czbs2zk9z5kz5dyvfbny.jpg", 
            "location": "San Antonio", 
            "name": "Geekdom Fund", 
            "schools": [
                {
                    "country": "United States", 
                    "description": "Stanford University Graduate School of Business", 
                    "idnum": 3, 
                    "image_url": "https://crunchbase-production-res.cloudinary.com/image/upload/c_pad,h_140,w_140/v1481309706/olvayk18i7e3t1mptejq.jpg", 
                    "location": "Stanford", 
                    "name": "Stanford University Graduate School of Business", 
                    "size": 1000, 
                    "website": "http://www.gsb.stanford.edu"
                }
            ],
            "website": "http://www.geekdomfund.com"
        }