select * from COMPANY;
select * from CB_OBJECTS;

INSERT INTO COMPANY(NAME, LOCATION, OWNERSHIP_TYPE, FUNDING, DESCRIPTION, CEO_ID, IMAGE_URL, SIZE, WEBSITE, CRUNCH_ID)
SELECT CBO.NAME, 
CASE WHEN CBO.CITY IS NULL THEN CASE WHEN CBO.REGION IS NULL THEN CBO.STATE_CODE ELSE CBO.REGION END ELSE CBO.CITY END, 
NULL, CBO.FUNDING_TOTAL_USD, 
CASE WHEN CBO.OVERVIEW IS NULL OR LENGTH(CBO.OVERVIEW) > 349 THEN CASE WHEN CBO.DESCRIPTION IS NULL THEN CBO.SHORT_DESCRIPTION ELSE CBO.DESCRIPTION END ELSE CBO.OVERVIEW END, 
NULL, CBO.LOGO_URL, NULL, CBO.DOMAIN, CBO.ID
FROM CB_OBJECTS AS CBO;
