UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%CEO%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%Chief Executive Officer%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%Founder%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%founder%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%Owner%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%owner%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%Chairman%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%ceo%' AND COMPANY.CEO_ID IS NULL;

UPDATE COMPANY
SET CEO_ID = PERSON.IDNUM
FROM PERSON
WHERE PERSON.NAME = COMPANY.CRUNCH_ID AND PERSON.TITLE LIKE '%President%' AND COMPANY.CEO_ID IS NULL;

SELECT * FROM EMPLOYMENT;

INSERT INTO EMPLOYMENT(PERSON_ID, COMPANY_ID)
SELECT P.IDNUM, C.IDNUM
FROM PERSON P
JOIN COMPANY C ON P.NAME = C.CRUNCH_ID;

