UPDATE COMPANY 
SET OWNERSHIP_TYPE = CASE 
WHEN exists(select 1 from CB_IPOS where OBJECT_ID=CRUNCH_ID) 
THEN OWNERSHIP('PUBLIC') ELSE OWNERSHIP('PRIVATE') END;

UPDATE COMPANY 
SET OWNERSHIP_TYPE = OWNERSHIP('PRIVATE')
WHERE IDNUM=3364;

select * from company;
select * from cb_ipos;
