INSERT INTO PERSON(NAME,TITLE,LOCATION,DOB,IMAGE_URL,WEBSITE, CRUNCH_ID)
SELECT CBO.relationship_object_id, CBO.TITLE, NULL, NULL, NULL, NULL, CBO.person_object_id
FROM CB_RELATIONSHIPS AS CBO JOIN COMPANY AS C ON CBO.relationship_object_id = C.CRUNCH_ID;

select * from person;
